export const SIGNUP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGNUP_FAILURE = "SIGN_UP_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
